### ISSUE TITLE
Required internet during the pipeline analysis

### ISSUE THREAD

**Issue by adamkoletis** [epi2me-labs/wf-artic#23]
![Screenshot from 2021-12-01 11-01-31](https://user-images.githubusercontent.com/93767749/144223731-c2aa5435-aa01-4a39-bde3-d4b9bb0279f2.png)
Please we face the above issue.With no connection internet cannot proceed the pipeline.

**Comment by mattdmem** [comment]
Sorry about this, we'll push an update to fix. If you want to get it working in the meantime then change the nextflow pangolin process to include a check for internet connectivity like below. If you run without connectivity you won't get the most up to date pangolin, however.

```
process pangolin {
    label "pangolin"
    cpus 1
    input:
        path "consensus.fasta"
    output:
        path "lineage_report.csv", emit: report
        path "pangolin.version", emit: version
    """
    # Check to see if the box running the workflow has internet connectivity
    echo -e "GET http://nanoporetech.com HTTP/1.0\n\n" | nc nanoporetech.com 80 > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        pangolin --update
    else
        echo "Offline"
    fi
    pangolin --update
    pangolin --all-versions 2>&1 | sed 's/: /,/' > pangolin.version
    pangolin consensus.fasta
    """
}
```

**Comment by mattdmem** [comment]
sorry - edit to the above - turns out nc is not installed in the docker image for pangolin
```
process pangolin {
    label "pangolin"
    cpus 1
    input:
        path "consensus.fasta"
    output:
        path "lineage_report.csv", emit: report
        path "pangolin.version", emit: version
    """
    # Check to see if the box running the workflow has internet connectivity
    EXIT_CODE=0
    wget -q --spider --timeout 10 http://nanoporetech.com || EXIT_CODE=\$?

    if [ \${EXIT_CODE} -eq 0 ]; then
        pangolin --update
    else
        echo "Offline"
    fi
    
    pangolin --all-versions 2>&1 | sed 's/: /,/' > pangolin.version
    pangolin consensus.fasta
    """
}
```

**Comment by mattdmem** [comment]
@adamkoletis this is fixed as of v0.3.7

**Comment by adamkoletis** [comment]
Hi 
Please. I had followed the update but
1)The CHANGELOG.md does not getting any update, I mean showing until v0.3.5
2)Still appears issue with pangolin and internet needs.
Thanks

**Comment by mattdmem** [comment]
how are you running the workflow?

If you do the following it should pull the latest version
`nextflow run epi2me-labs/wf-artic -latest`

If you have cloned the repo then you likely need to pull the latest verison:
```
cd wf-artic
git fetch --tags
git checkout v0.3.7
```

**Comment by mattdmem** [comment]
There is a blog post that explains how to manage our workflows here:
https://labs.epi2me.io/managing-epi2me-labs-workflows-with-the-nextflow-command-line-interface/
